### ISSUE TITLE
No sandbox integration

### ISSUE THREAD

**Issue by ndjdev** [eversign/eversign-python-sdk#3]
It doesn't appear as if the sandbox parameter is included anywhere in the SDK?

Thanks

**Comment by dominikkukacka** [comment]
We will implement it as fast as possible!

**Comment by ndjdev** [comment]
👍

**Comment by dominikkukacka** [comment]
we just released 1.1 (https://pypi.org/project/eversign/1.1/) which adds this feature.

**Comment by clmns** [comment]
You can set the sandbox attribute on Document and Template types now

**Comment by ndjdev** [comment]
Amazing thanks, changes look great!

**Comment by ndjdev** [comment]
Sorry this still isn't working, it looks like just the examples have been updated. The sandbox parameter isn't being passed to the API at all as far as I can tell, there are no instances of the word "sandbox" anywhere in the document file https://github.com/eversign/eversign-python-sdk/blob/master/eversign/document.py

**Comment by clmns** [comment]
The change was somehow lost in space, but is now back :) Sorry for the hassle. The package was updated in pypi.

**Comment by ndjdev** [comment]
Great thanks :)
